name: Compiler for RPi

on:
  push:
    branches:
      - master
    paths:
      - "rpi.config"
  # schedule:
  #   - cron: 0 18 * * 5
  # watch:
  #   types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Initialize environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          sudo -E apt-mark hold grub-efi-amd64-signed
          sudo -E apt update
          sudo -E apt -y purge azure-cli* docker* ghc* zulu* llvm* firefox google* dotnet* powershell* openjdk* mysql* php* mongodb* dotnet* snap*
          sudo -E apt -y full-upgrade
          sudo -E apt -y install ack antlr3 aria2 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
          sudo -E systemctl daemon-reload
          sudo -E apt -y autoremove --purge
          sudo -E apt clean
          sudo -E timedatectl set-timezone "Asia/Shanghai"

      - name: Clone lean LEDE
        env:
          REPO_URL: https://github.com/coolsnowwolf/lede.git
          REPO_BRANCH: master
        run: |
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
          df -h

      - name: Update & install feeds
        run: |
          cd openwrt
          echo 'src-git helloworld https://github.com/fw876/helloworld' >> ./feeds.conf.default
          ./scripts/feeds update -a && ./scripts/feeds install -a
          echo "feeds.conf.default:" && cat ./feeds.conf.default

      - name: Load config
        run: |
          [ -e rpi.config ] && mv rpi.config openwrt/.config

      - name: Download package
        run: |
          cd openwrt && make download -j8
          find dl -size -1024c -exec rm -f {} \;

      - name: Build
        run: |
          cd openwrt
          make -j$(nproc) V=s
          # make -j1 V=s

      - name: Space usage
        run: |
          df -h

      - name: Upload all firmwares
        uses: actions/upload-artifact@master
        with:
          name: All Firmwares
          path: openwrt/bin/targets/

      - name: Upload package
        uses: actions/upload-artifact@master
        with:
          name: All Packages
          path: openwrt/bin/packages/
