name: Compiler for K3

on:
  push:
    branches:
      - master
    paths:
      - 'k3.config'
  # schedule:
  #   - cron: 0 18 * * 5
  # watch:
  #   types: [started]
    
jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialize environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi `docker images -q`
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
        sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*        
        sudo -E apt-get update
        sudo -E apt-get install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf
        sudo -E apt-get autoremove --purge
        sudo -E apt-get clean

    - name: Clone lean LEDE
      env: 
        REPO_URL: https://github.com/coolsnowwolf/lede
        REPO_BRANCH: master
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        df -h

    - name: Update & install feeds
      run: |
        cd openwrt
        sed -i 's/#src-git/src-git/g' ./feeds.conf.default
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        echo "feeds.conf.default:"
        cat ./feeds.conf.default

    - name: Load config
      run: |
        [ -e k3.config ] && mv k3.config openwrt/.config

    - name: Download package
      run: |
        cd openwrt && make download -j8
        find dl -size -1024c -exec rm -f {} \;

    - name: Build
      run: |
        # cd openwrt && make -j1 V=s
        cd openwrt
        echo -e "$(nproc) thread build."
        make -j$(nproc) V=s

    - name: Space Usage
      run: |
        df -h

    - name: Upload firmware
      uses: actions/upload-artifact@master
      with:
        name: K3_Firmware
        path: openwrt/bin/targets/
