name: Compiler for J4125

on:
  push:
    branches:
      - master
    paths:
      - "x86.config"
  # schedule:
  #   - cron: 0 18 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Initialize environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mysql* php* mongodb* dotnet* moby* snapd* || true
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig libtinfo5
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

      - name: Clone lean LEDE
        env:
          REPO_URL: https://github.com/coolsnowwolf/lede.git
          REPO_BRANCH: master
        run: |
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
          df -h

      - name: Update & install feeds
        run: |
          cd openwrt
          echo 'src-git helloworld https://github.com/fw876/helloworld.git' >> ./feeds.conf.default
          echo 'src-git passwall https://github.com/xiaorouji/openwrt-passwall2' >> ./feeds.conf.default
          ./scripts/feeds update -a && ./scripts/feeds install -a
          echo "feeds.conf.default:" && cat ./feeds.conf.default
          sed -i 's/KERNEL_PATCHVER:=6.6/KERNEL_PATCHVER:=5.15/' ./target/linux/x86/Makefile
          sed -i 's/KERNEL_TESTING_PATCHVER:=6.12/KERNEL_TESTING_PATCHVER:=6.1/' ./target/linux/x86/Makefile
          echo "Makefile:" && cat ./target/linux/x86/Makefile

      - name: Load config
        run: |
          [ -e x86.config ] && mv x86.config openwrt/.config

      - name: Download package
        run: |
          cd openwrt && make download -j8
          find dl -size -1024c -exec rm -f {} \;

      - name: Build
        run: |
          cd openwrt
          make -j$(nproc) V=s
          # make -j1 V=s

      - name: Space usage
        run: |
          df -h

      - name: Upload firmwares
        uses: actions/upload-artifact@master
        with:
          name: Firmwares
          path: openwrt/bin/targets/

      - name: Upload package
        uses: actions/upload-artifact@master
        with:
          name: Packages
          path: openwrt/bin/packages/
