name: LEDE for Raspberry Pi

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 8 * * 5
    
jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialize Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi `docker images -q`
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
        sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*        
        sudo -E apt-get update
        sudo -E apt-get install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf
        sudo -E apt-get autoremove --purge
        sudo -E apt-get clean
        df -h

    - name: Clone Lean LEDE
      env: 
        REPO_URL: https://github.com/coolsnowwolf/lede
        REPO_BRANCH: master
      run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt

    - name: Update Feeds
      run: |
        cd openwrt
        sed -i 's/#src-git helloworld/src-git helloworld/g' ./feeds.conf.default
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        cat ./feeds.conf.default

    - name: Load Config File
      run: |
        [ -e pi.config ] && mv pi.config openwrt/.config

    - name: Download Package
      run: |
        cd openwrt && make download -j8
        find dl -size -1024c -exec rm -f {} \;

    - name: Build
      run: |
        # cd openwrt && make -j1 V=s
        cd openwrt
        echo -e "$(nproc) thread build."
        make -j$(nproc) V=s

    - name: Space Usage
      run: |
        df -h

    - name: Upload Packages Directory
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt_Packages
        path: openwrt/bin/packages/

    - name: Upload Targets Directory
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt_Firmware
        path: openwrt/bin/targets/
