name: Remove old artifacts

on:
  # push:
  #   branches:
  #     - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '15 days'
        skip-tags: true
